// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNg95jwIEtyX0aIGSoNqWcxJBJA5yvax0',
    appId: '1:1053257691964:android:c590bb2387c2a5003d2439',
    messagingSenderId: '1053257691964',
    projectId: 'prueba-4eea4',
    databaseURL: 'https://prueba-4eea4-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-4eea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnWDi-yW_57E59-6ZzI3SmEcNWWolYKQ',
    appId: '1:1053257691964:ios:6a41176c22fa88873d2439',
    messagingSenderId: '1053257691964',
    projectId: 'prueba-4eea4',
    databaseURL: 'https://prueba-4eea4-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-4eea4.firebasestorage.app',
    iosBundleId: 'com.example.optiflutter',
  );
}
